version: '2'
services:
  ffmpeg:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - no_proxy=${no_proxy}
    tty: true
    restart: always
    volumes:
      - $PWD/volume:/workspace
