version: '2'
services:
  ffmpeg:
    build:
      context: .
      args:
        - HTTP_PROXY=${http_proxy}
        - HTTPS_PROXY=${https_proxy}
        - NO_PROXY=${no_proxy}
    restart: always
    volumes:
      - $PWD:/workspace
