FROM ubuntu:16.04

ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND noninteractive

WORKDIR workspace

SHELL ["/bin/bash", "-c"]

# RUN START 
RUN apt-get -y update && \
    apt-get -y install git autoconf \
                       automake \
                       build-essential \
                       cmake \
                       git-core \
                       libass-dev \
                       libfreetype6-dev \
                       libsdl2-dev \
                       libtool \
                       libva-dev \
                       libvdpau-dev \
                       libvorbis-dev \
                       libxcb1-dev \
                       libxcb-shm0-dev \
                       libxcb-xfixes0-dev \
                       pkg-config \
                       texinfo \
                       wget \
                       zlib1g-dev  \
                       libfdk-aac-dev && \
    cd /tmp && \
    git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg && \
    cd ffmpeg && \
    git -C fdk-aac pull 2> /dev/null || git clone --depth 1 https://github.com/mstorsjo/fdk-aac && \
    cd fdk-aac && \
    autoreconf -fiv && \
    ./configure --prefix="/tmp/ffmpeg_build" --disable-shared && \
    make && \
    make install && \
    chmod 0777 /workspace && \
    apt-get -y clean && \
    history -c